do_you_want_to_continue=続行しますか？ ({{y/n}}):

catfood_warning=<@w>警告: キャットフードの編集は BAN の原因になる可能性があります。自己責任で使用してください。</>\n{{do_you_want_to_continue}}
legend_ticket_warning=<@w>警告: レジェンドチケットの編集は BAN の原因になる可能性があります。自己責任で使用してください。</>\n{{do_you_want_to_continue}}
rare_ticket_warning=
><@w>警告: レアチケットの編集は BAN の原因になる可能性があります。自己責任で使用してください。</>
>レアチケットを低リスクで入手するにはレアチケット交換機能を使用できます。
platinum_ticket_warning=
><@w>警告: プラチナチケットの編集は BAN の原因になる可能性があります。自己責任で使用してください。</>
>プラチナシャード機能を使うと低リスクでプラチナチケットを得ることができます。

select_an_option_to_continue=編集を続行するオプションを選択してください {feature_name}:

continue_editing={feature_name} の編集を続行
go_to_safe_feature=より安全な {safer_feature_name} 機能へ移動
cancel_editing={feature_name} の編集をキャンセル

rare_ticket_trade_enter=追加するレアチケットの数を入力してください (最大値: <@q>{max}</>) (現在: <@q>{current}</>):
rare_ticket_trade_storage_full=<@e>エラー: 猫保管庫に空きがありません。空きを1つ以上確保してください！</>
rare_ticket_successfully_traded=
><@su>{rare_ticket_count} 枚のレアチケットを付与しました。</>
>猫保管庫に入り、<@q>すべて使用</> ボタンを押し、その後 <@q>チケットと交換</> ボタンを押してチケットを獲得してください。

rare_tickets_l=レアチケット
rare_ticket_trade_l=レアチケット交換

rare_ticket_trade_maxed=<@e>エラー: 既にレアチケットの上限に達しています！\n使用してから再度実行してください！

platinum_tickets_l=プラチナチケット
platinum_shards_l=プラチナシャード