total_selected_enemies=<@t>{total}</> 匹の敵が選択されています
unlock_enemy_guide_success=<@su>敵図鑑のエントリを正常に解放しました</>
remove_enemy_guide_success=<@su>敵図鑑のエントリを正常に削除しました</>
selected_enemy=<@t>{name}</> (<@t>{id}</>) が選択されています
select_enemies_valid=敵図鑑にあるすべての敵を選択
select_enemies_invalid=敵図鑑に無い敵をすべて選択
select_enemies_all=すべての敵を選択
select_enemies_id=ID で敵を選択
select_enemies_name=名前で敵を選択
select_enemies=敵を選択:
enter_enemy_ids=敵 ID は次で確認できます: <@t>https://battlecats.miraheze.org/wiki/Enemy_Release_Order</>\n敵 ID を入力 {{range_input}}:
enter_enemy_name=敵の名前を入力:
enemy_not_found_name=<@w>名前 <@s>{name}</> の敵は見つかりませんでした</>
unlock_enemy_guide=敵図鑑を解放
remove_enemy_guide=敵図鑑のエントリを削除
enemy_guide=敵図鑑
edit_enemy_guide=敵図鑑のエントリを編集するオプションを入力:
