enter_raw_gamatoto_xp=生のガマトト XP を入力
enter_gamatoto_level=ガマトトのレベルを入力
edit_gamatoto_level_q=ガマトトのレベルを編集するオプションを入力:
gamatoto_xp=ガマトト XP
gamatoto_level=ガマトト レベル
gamatoto_level_success=<@su>ガマトトのレベルを <@s>{level}</> に設定しました (XP: <@s>{xp}</>)</>
gamatoto_level_current=<@t>現在のガマトトレベル: <@q>{level}</> (XP: <@q>{xp}</>)</>
gamatoto_xp_level=ガマトト XP / レベル

current_gamatoto_helpers=現在のヘルパー:
gamatoto_helper=ヘルパー: <@t>{name}</> (レアリティ: <@t>{rarity_name}</>)

new_gamatoto_helpers=新しいヘルパー:
gamatoto_helpers=ガマトトヘルパー

ototo_cat_cannon=オトトキャットキャノン

current_cannon_stats=現在のキャノンステータス:

cannon_part=<@t><@q>{name}</>{buffer}(レベル <@s>{level}</>)</>
development={buffer}(成長: <@q>{development}</>)
cannon_stats={parts}

foundation=基礎
style=スタイル
effect=効果
improved_foundation=改良された基礎
improved_style=改良されたスタイル

unknown_stage=不明な段階 (<@s>{stage}</>)

selected_cannon=<@t>選択されたキャノン: <@q>{name}</></>
selected_cannon_stage=<@t>キャノン: <@q>{name}</> 現在の段階: <@q>{stage}</></>

cannon_edit_type=各キャノンを個別に編集しますか、それとも選択したすべてに一括で適用しますか?:

cannon_dev_level_q=キャノンの成長を編集しますか、それともレベルを編集しますか?:
development_o=成長
level_o=レベル

select_development=成長段階を選択:
select_cannon=キャノンを選択
cannon_level=キャノンレベル

cannon_success=<@su>オトトキャノンを正常に編集しました</>

cat_shrine=猫の祠を編集
shrine_level=祠レベルを編集
shrine_xp=祠 XP
current_shrine_xp_level=<@t>現在の XP: <@q>{xp}</> (レベル: <@q>{level}</>)</>
cat_shrine_choice_dialog=何を実行しますか?:
shrine_level_dialog=祠レベルを入力してください (最大: <@q>{max_level}</>):
shrine_xp_dialog=祠 XP を入力してください (最大: <@q>{max_xp}</>):
cat_shrine_edited=<@su>猫の祠を正常に編集しました</>
make_catshrine_appear=ゲーム内に祠を表示
make_catshrine_disappear=ゲーム内から祠を非表示
