event_tickets=イベントチケット / ラッキーチケット
downloading_gatya_data=ガチャイベントデータをダウンロードしています...
download_gatya_data_success=<@su>ガチャイベントデータを正常にダウンロードしました</>
download_gatya_data_fail=<@e>ガチャイベントデータのダウンロードに失敗しました。再試行してください</>
save_gatya_error=<@e>ガチャデータの保存に失敗しました: {error}</>
gatya_by_id_q=ガチャバナーを <@t>ID</> で選択しますか、それとも <@t>名前</> で選択しますか?:
by_id=ID で
by_name=名前で
