gold_pass_dialog=取得したい <@t>役員 ID</> を入力してください (空欄でランダム、または <@q>-1</> を入力すると削除します):
gold_pass=ゴールドパス / オフィサークラブ
gold_pass_remove_success=<@su>ゴールドパスを正常に削除しました</>
gold_pass_get_success=<@su>ゴールドパスを正常に取得しました (ID: <@t>{id}</>)</>。<@w>注: 実際に所持していない場合、ゲーム側でゴールドパスが取り消される可能性があります。これは修正不可能です。</>
officer_pass_fixed=<@su>オフィサークラブのクラッシュを修正しました</>
fix_officer_pass_crash=オフィサークラブのクラッシュを修正
