# Note that not all items are here

catamins=キャタミン
catfruit=キャットフルーツ
base_materials=素材
inquiry_code=問い合わせコード
rare_gatya_seed=レアガチャシード
normal_gatya_seed=通常ガチャシード
event_gatya_seed=イベントガチャシード
unlocked_slots=アンロックされたスロット|装備スロット|編成
password_refresh_token=パスワードリフレッシュトークン
challenge_score=チャレンジスコア
dojo_score=道場スコア
items=アイテム
user_rank_rewards=ユーザーランクリワードを受け取る (報酬は付与されません)

catfood=キャットフード
xp=経験値
normal_tickets=通常チケット|基本チケット|銀チケット
rare_tickets=レアチケット|金チケット
platinum_tickets=プラチナチケット
legend_tickets=レジェンドチケット
100_million_tickets=1億ダウンロードチケット|1 Hundred Million Downloads Tickets
100_million_warn=<@w>注: 1億ダウンロードイベントが有効な場合にのみチケットが表示・使用できます</>
platinum_shards=プラチナシャード
np=NP
leadership=リーダーシップ
catseyes=キャットシーズ
battle_items=バトルアイテム
duration=<@t>{days}</t> 日, <@t>{hours}</t> 時間, <@t>{minutes}</> 分, <@t>{seconds}</> 秒
endless_item_item=<@s>{item}</> : <@s>{int}</>
endless_items_success=<@su>無限アイテムを正常に編集しました</>
invalid_minute_count=<@e>無効な分数です</>
enter_duration_minutes=無限アイテムの継続時間（分）を入力してください ( <@t>infinity</> を入力すると無期限になります):
infinity_duration=<@t>無期限</>
infinity=無期限
enter_duration_minutes_item=<@t>{item}</> の継続時間（分）を入力してください ( <@t>infinity</> を入力すると無期限になります):
battle_items_endless=無限バトルアイテム
talent_orbs=才能オーブ
scheme_items=スキームアイテム
labyrinth_medals=ラビリンスメダル
restart_pack=リスタートパック|リターナーモード
engineers=エンジニア
gamototo=ガマトト / オトト
special_skills=特殊スキル / 基礎能力
treasure_chests=宝箱
unknown_treasure_chest_name=不明な宝箱 ({id})

rare_ticket_trade=レアチケット交換
rare_ticket_trade_feature_name=レアチケット交換 (BAN リスクの低いレアチケットを提供)

other=その他
gatya=ガチャ
levels=ステージ / ストーリー / 宝
cats_special_skills=猫 / 特殊スキル

gatya_item_unknown_name=不明なアイテム
unknown_catamin_name=不明なキャタミン <@t>{id}</>
unknown_catseye_name=不明なキャットシーズ <@t>{id}</>
unknown_catfruit_name=不明なキャットフルーツ <@t>{id}</>
unknown_labyrinth_medal_name=不明なラビリンスメダル <@t>{id}</>

reset_golden_cat_cpus_success=<@su>ゴールデンキャットの CPU 使用をリセットしました</>
reset_golden_cat_cpus=ゴールデンキャットの CPU 使用をリセット
