medals=ミャウメダル
add_medals=メダルを追加
remove_medals=メダルを削除
medal_add_remove_dialog=メダルを <@t>追加</> しますか、それとも <@t>削除</> しますか?:
medal_string={medal_name}: <@q>{medal_req}</>
select_medals=メダルを選択:
medals_added=<@su>ミャウメダルを正常に追加しました</>
medals_removed=<@su>ミャウメダルを正常に削除しました</>