missions=キャットニップチャレンジ / ミッション | キャットミッション
complete_reward=ミッションをクリアして報酬を受け取らない
complete_claim=ミッションをクリアして報酬を受け取る
uncomplete=ミッションを未完了にする
select_mission_claim=ミッションを <@t>クリアするが報酬を受け取らない</>、<@t>クリアして報酬を受け取る</> (<@q>実際には報酬は付与されません</>)、または <@t>未完了にする</> のどれを行いますか?:
select_missions=編集するミッションを選択:
missions_edited=<@su>ミッションを正常に編集しました</>