playtime_str=<@t>{hours}</> $(hours: !=1($hours)$, hour)/$, <@t>{minutes}</> $(minutes: !=1($minutes)$, minute)/$, <@t>{seconds}</> $(seconds: !=1($seconds)$, second)/$ (<@t>{frames} </>$(frames: !=1($frames)$, frame)/$)
playtime_current=現在のプレイ時間: {{playtime_str}}
playtime_edited=プレイ時間を正常に編集しました: {{playtime_str}}
playtime_hours_prompt=設定する <@t>時間</> の数を入力してください:
playtime_minutes_prompt=設定する <@t>分</> の数を入力してください:
playtime_seconds_prompt=設定する <@t>秒</> の数を入力してください:
playtime=プレイ時間