scheme_items_edit_success=<@su>スキームアイテムを正常に編集しました</>
scheme_items_select_gain=入手するスキームアイテムを選択
scheme_items_select_remove=削除するスキームアイテムを選択
gain_remove_scheme_items=スキームアイテムを <@t>入手</> しますか、それとも <@t>削除</> しますか?:
gain_scheme_items=スキームアイテムを入手
remove_scheme_items=スキームアイテムを削除