special_skills_dialog=強化する基礎能力を選択
upgrade_individual_skill=各選択スキルに対して強化を入力
upgrade_all_skills=選択したすべてのスキルに適用する強化を入力

upgrade_skills_select_mod=スキルを強化するオプションを選択:

selected_skill=<@t>{name}</> が選択されています
selected_skill_upgrades={{selected_skill}}: <@t>{base_level}<@s>+</>{plus_level}
selected_skill_upgraded=<@t>{name}</> が <@t>{base_level}<@s>+</>{plus_level} に強化されました
skills_edited=<su>特殊スキルを正常に編集しました</>