total_current_orbs=現在のオーブ総数: <@q>{total_orbs}</>
total_current_orb_types=現在のオーブ種類数: <@q>{total_types}</>
current_orbs=現在のオーブ:
orb_select=編集する才能オーブを選択:
selected_orbs=選択された才能オーブ:
edit_orbs_individually=各オーブを個別に編集しますか (<@q>1</>)、それとも一括 (<@q>2</>) しますか?:
edit_orbs_all=選択したすべてのオーブに設定する値を入力 (最大 <@t>{max}</>):
failed_to_load_orbs=才能オーブの読み込みに失敗しました

edit_orbs_help=
>ヘルプ:
>利用可能なグレード: {all_grades_str}
>利用可能な属性: {all_attributes_str}
>利用可能な効果: {all_effects_str}
><@w>注: すべての属性に対して全てのグレードや効果が存在するわけではありません。</>
>入力例:
>    <c>aku</> - すべての <c>aku</> オーブを選択
>    <r>red</> <b>s</> - <r>赤</> の <b>s</> グレードを選択
>    <b>alien</> <r>d</> <r>0</> - <b>alien</> 属性の <r>d</> グレードで攻撃を上げるオーブを選択
>    <o>c</> <dm>1</> - ブースト Stories of Legend のオーブでグレード <o>c</>
>すべてのオーブを選択するには:
>    <@q>*</>
>複数選択する場合はカンマで区切ります:
>    <b>s</> <bl>black</> <g>4</>,<r>d</> <o>3</>,<g>floating</>
>

