whole_chapters=章単位
individual_stages=個別ステージ
treasure_groups=宝グループ / セット
treasure_dialog=宝を <@t>章単位で一括</>、<@t>個別ステージ</>、または <@t>宝グループ</> ごとに編集しますか?:
treasures_edited=<@su>宝を正常に編集しました</>
per_chapter=章ごと
all_selected_chapters=選択したすべての章
edit_per_chapter=すべての選択章に対してデータを編集しますか、それとも各章を個別に編集しますか?:
no_treasure=宝なし
custom_treasure_level=カスタム宝レベル (<@w>分かっている場合のみ編集してください！</>)
treasure_level_dialog=設定する宝レベルを入力してください:
custom_treasure_level_dialog=設定するカスタム宝レベルを入力してください:
select_stage_by_id=ID でステージを選択
select_stage_by_name=名前でステージを選択
select_stage_dialog=ID で選択しますか、それとも名前で選択しますか?:
select_stage_id=選択するステージ ID を入力 {{range_input}}
select_stages_name=ステージを選択:
select_treasure_groups=編集する宝グループを選択:
story_treasures=ストーリートレジャー
current_chapter=現在の章: <@t>{chapter_name}</>
current_treasure_group=現在の宝グループ: <@t>{treasure_group_name}</>
group_individual=個別グループ
group_all_at_once=選択したすべてのグループ
select_treasure_groups_individual=各 <@t>宝グループ</> の宝レベルを個別に編集しますか、それとも <@t>すべて</> を一括で編集しますか?:
