claim=受け取る
unclaim=取り消す
fix_claimed=受取状態を修正
claim_or_unclaim_ur=ユーザーランクリワードを <@t>受け取る</>、<@t>取り消す</>、または <@t>受取状態を修正 (現在のランクより上の報酬を取り消す)</> しますか?:
select_ur=ユーザーランクリワードを選択
ur_claimed_success=<@su>ユーザーランクリワードを正常に受け取りました</>
ur_unclaimed_success=<@su>ユーザーランクリワードの受取を正常に取り消しました</>
ur_string=ランク: <@s>{rank}</>: {description}
ur_fix_claimed_success=<@su>受取状態を正常に修正しました</>