another_path=手動でパスを入力
select_files_dir=ディレクトリ内のファイルを選択:
enter_path=ファイルパス / 場所を入力してください:
enter_path_dir=フォルダパス / 場所を入力してください:
enter_path_default=ファイルパス / 場所を入力してください (デフォルト: <@t>{default}</>):
current_files_dir=現在のディレクトリ内のファイル <@t>{dir}</>:
other_dir=他のディレクトリを入力
no_files_dir=<@e>ディレクトリにファイルがありません</>
path_not_exists=<@e>パスが存在しません</>