save_load_option=セーブファイルを読み込むオプションを選択
download_save=転送コードと確認コードを使用してセーブをダウンロード
select_save_file=ファイルからセーブを選択
adb_pull_save=adb を使ってデバイスからセーブを取得
waydroid_pull_save=Waydroid デバイスからセーブを取得
load_save_data_json=JSON からセーブデータを読み込む
root_storage_pull_save=ルートストレージからセーブを取得
save_save_dialog=セーブファイルを保存
save_downloaded=<@su>セーブファイルを <@s>{path}</> にダウンロードしました</>
save_json_dialog=セーブデータを JSON に保存
load_from_documents=ドキュメントフォルダからセーブを読み込む
save_file_not_found=<@e>セーブファイルが見つかりません</>
save_file_found=<@su>セーブを読み込んでいます: <@t>{path}<@t></>

parse_save_error=<@e>セーブファイルの解析中にエラーが発生しました: {error}\n(エディタバージョン: <@s>{version}</>) (ゲームバージョン: <@s>{game_version}</>) (国コード: <@s>{country_code}</>)\n{{report_message}}</>
load_json_fail=<@e>JSON からセーブデータの読み込みに失敗しました ({error})</>
editor_version_mismatch=<@w>エディタ バージョンの不一致。セーブファイルはこのエディタと互換性がない可能性があります。Json バージョン: <@t>{json_version}</>, エディタバージョン: <@t>{editor_version}</></>
save_management=セーブ管理
save_save=セーブを保存
save_save_file=特定ファイルにセーブを保存
save_save_documents=ドキュメントフォルダにセーブを保存
save_upload=セーブファイルをサーバへアップロードして転送コードと確認コードを取得
unban_account=アカウントのアンバン / "別の場所で使用された" エラーを修正

adb_push_rerun=adb を使ってセーブをデバイスにプッシュする (プッシュ後にゲームを再起動)
adb_push=adb を使ってセーブをデバイスにプッシュする (ゲームは再起動しない)
adb_push_success=<@su>セーブファイルをデバイスにプッシュしました</>
adb_push_fail=<@e>セーブファイルのプッシュに失敗しました</> ({error})
adb_rerun_success=<@su>ゲームを正常に再起動しました</>
adb_rerun_fail=<@e>ゲームの再起動に失敗しました</> ({error})

waydroid_push_rerun=Waydroid デバイスへセーブをプッシュする (プッシュ後にゲームを再起動)
waydroid_push=Waydroid デバイスへセーブをプッシュする (ゲームは再起動しない)
waydroid_push_success=<@su>セーブファイルを Waydroid デバイスにプッシュしました</>
waydroid_push_fail=<@e>Waydroid デバイスへのプッシュに失敗しました</> ({error})
waydroid_rerun_success=<@su>Waydroid デバイス上でゲームを正常に再起動しました</>
waydroid_rerun_fail=<@e>Waydroid デバイスでゲームを再起動できませんでした</> ({error})

export_save=セーブを JSON にエクスポート
save_success=<@su>セーブファイルを <@s>{path}</> に保存しました
export_success=<@su>セーブデータを <@s>{path}</> にエクスポートしました
init_save=セーブをリセット
init_save_confirm=セーブをリセットしてもよいですか？ ({{y/n}}):
init_save_success=<@su>セーブを正常にリセットしました</>

adb_pulling=<@q>パッケージ名 <@s>{package_name}</> のデバイスから adb でセーブを取得しています ...</>
adb_pull_fail=<@e>パッケージ名 <@s>{package_name}</> のデバイスから adb でセーブを取得できませんでした ({error})

waydroid_pulling=<@q>パッケージ名 <@s>{package_name}</> の Waydroid からセーブを取得しています ...</>
waydroid_pull_fail=<@e>パッケージ名 <@s>{package_name}</> の Waydroid からセーブを取得できませんでした ({error})

storage_pulling=<@q>パッケージ名 <@s>{package_name}</> のルートストレージからセーブを取得しています...</>
storage_pull_fail=<@e>パッケージ名 <@s>{package_name}</> のルートストレージからセーブを取得できませんでした ({error})

not_rooted_error=<@e>デバイスが root 化されていない、またはエディタが root 権限で実行されていない可能性があります</>

upload_items=管理アイテムをサーバにアップロード
upload_items_success=<@su>管理アイテムを正常にアップロードしました</>
upload_items_fail=<@e>管理アイテムのアップロードに失敗しました</>

load_save=セーブを読み込む
load_save_success=<@su>セーブを正常に読み込みました</>
account=アカウント

save_before_exit=<@q>終了前に最新の変更を保存しますか？ (<@s>y</>/<@s>n</>):</>
save_temp_success=<@su>一時ファイルからセーブを復元しました</>
save_temp_fail=<@e>一時ファイルからセーブを復元できませんでした。最新の変更は失われました</> ({error})\n{traceback}
save_temp_not_found=<@e>一時ファイルが見つからず、セーブの復元に失敗しました。最新の変更は失われました</> (一時ファイルが見つかりません)

cant_detect_cc=<@w>セーブから国コードを検出できませんでした。\n国コードを手動で入力してください</>
failed_to_load_save_gv=セーブは読み込まれましたが、予期しない値が含まれていました。セーブ破損を防ぐためにエラーが発生しました
failed_to_load_save=セーブの読み込みに失敗しました
failed_to_save_save=セーブの保存に失敗しました

game_version_dialog=ゲームバージョンを入力してください (例: <@t>12.2.1</>):
invalid_game_version=<@e>無効なゲームバージョンです</>
country_code_set=<@su>国コードを <@s>{cc}</> に設定しました</>
game_version_set=<@su>ゲームバージョンを <@s>{version}</> に設定しました</>

convert_region=国コードを変換 (例: en -\> jp)
convert_version=ゲームバージョンを変換 (例: 12.2.1 -\> 12.2.0)

cc_warning=<@w>警告: これを実行するとセーブファイルに問題が発生する可能性があります。不具合やクラッシュが予期されます。バグ報告する場合はこの機能を使用したことを明記してください。実行後に猫基地 / 強化メニューを開いて、ゲーム側で必要な変更が適用されるようにしてください。</>
gv_warning=<@w>警告: これを実行するとセーブファイルに問題が発生する可能性があります。不具合やクラッシュが予期されます。バグ報告する場合はこの機能を使用したことを明記してください。実行後に猫基地 / 強化メニューを開いて、ゲーム側で必要な変更が適用されるようにしてください。</>

create_new_save_success=<@su>新しいセーブファイルを正常に作成しました</>
create_new_save=新しいセーブファイルを作成
create_new_save_warning=<@w>警告: 自動作成されたセーブでは多くのエディタ機能が動作しない可能性があります。ゲームで一度ロードしてからエディタで再読み込みしてください。
これは将来のバージョンで変更される可能性があります。</>

parse_ignored_error=<@w>警告: <@e>{error}</>
<@w>Ignore Parse Error 設定が有効なため無視します。これにより問題が発生する可能性があります!</>

select_package_name=パッケージ名を選択:

adb_not_installed=
><@e>adb が PATH に追加されていないか、実行ファイルパスが間違っています。設定で adb パスを編集してください
>現在の値: <@s>{path}</>
>エラー: <@s>{error}</></>

waydroid_not_installed=<@e>Waydroid がインストールされていないか、エラーが発生しました: {error}</>

root_push_not_android_error=<@e>ルートプッシュは Android デバイスでのみ利用可能です</>
root_push_success=<@su>ルートストレージへセーブを書き込みました</>
root_push_fail=<@e>ルートストレージへの書き込みに失敗しました。エラー: <@s>{error}</></>

root_rerun_success=<@su>ゲームを正常に再起動しました</>
root_rerun_fail=<@e>ゲームの再起動に失敗しました。エラー: <@s>{error}</></>

root_push=ルートを使ってゲームに直接セーブをプッシュ
root_push_rerun=ルートを使ってゲームに直接セーブをプッシュ (ゲームを再起動)

select_recent=最近のセーブを選択:
recent_save=<@s><@q>{inquiry_code}</> <@t>{cc}</>-<@t>{gv}</> @ <@t>{year}</>-<@t>{month}</>-<@t>{day}</> <@t>{hour}</>:<@t>{minute}</>:<@t>{second}</> - 元のパス: <@q>{name}</></>

load_recent_saves=最近のセーブとバックアップから読み込む
no_recent_saves=<@w>最近のセーブはありません</>
current_save=\n現在のセーブ: <@t>{cc}</>-<@t>{gv}</> 問い合わせコード: <@t>{inquiry_code}</>
