transfer_code=転送コード
enter_transfer_code=転送コードを入力してください:
confirmation_code=確認コード
enter_confirmation_code=確認コードを入力してください:
country_code=国コード
country_code_select=国コードを選択:
invalid_codes_error=<@e>セーブのダウンロードに失敗しました。転送コード、確認コード、国コードを確認して再試行してください。</>
display_response_debug_info_q=レスポンスのデバッグ情報を表示しますか？ ({{y/n}}):
response_text_display=
>URL: <@q>{url}</>
>Request Headers: <@q>{request_headers}</>
>Request Body: <@q>{request_body}</>
>
>Response Headers: <@q>{response_headers}</>
>Response Body: <@q>{response_body}</>

downloading_save_file=サーバからセーブファイルをダウンロードしています (転送コード: <@q>{transfer_code}</>, 確認コード: <@q>{confirmation_code}</>, 国コード: <@q>{country_code}</>)...
upload_result=
><@su>
>転送コード: <@s>{transfer_code}</>
>確認コード: <@s>{confirmation_code}</>
></>

upload_fail=<@e>セーブファイルのアップロードに失敗しました。 {{try_again_message}} {{see_log}}</>
unban_fail=<@e>アカウントのアンバンに失敗しました。 {{try_again_message}} {{see_log}}</>
unban_success=<@su>アカウントのアンバンに成功しました。</>
upload_items_checker_confirm=一部の管理アイテムが現在のセーブで追跡されていません。今すぐアップロードしますか？ ({{y/n}}):
strict_ban_prevention_enabled=<@w>厳格な BAN 防止が有効です。セーブや管理アイテムをアップロードする前に新しいアカウントが作成されます。</>
create_new_account_success=<@su>アカウントを作成しました。</>
create_new_account_fail=<@e>アカウント作成に失敗しました。 {{try_again_message}} {{see_log}}</>

uploading_save_file=<@q>セーブファイルをサーバへアップロードしています...</>
getting_codes=<@q>転送コードと確認コードを取得しています...</>
getting_auth_token=<@q>アカウントの認証トークンを取得しています...</>
refreshing_password=<@q>アカウントのパスワードを更新しています...</>
getting_password=<@q>アカウントのパスワードを取得しています...</>
getting_save_key=<@q>アカウントのセーブキーを取得しています...</>

inquiry_code_warning=<@w>警告: 問い合わせコードを編集するとアカウントがプレイ不能になる可能性があります。自己責任で使用してください。</>
password_refresh_token_warning=<@w>警告: パスワードリフレッシュトークンを編集するとアカウントがプレイ不能になる可能性があります。自己責任で使用してください。</>

no_internet=<@e>インターネット接続がありません。接続を確認して再試行してください。</>

transfer_backup=<@su>バックアップ転送セーブを <@t>{path}</> に保存しました</>
transfer_backup_fail=<@e>バックアップ転送セーブを <@t>{path}</> に保存できませんでした: {error}</>

retry_auth_token=<@e>認証トークンの取得に失敗しました。再試行します...</>

downloading_compressed_data=<@su><@s>{url}</> からゲームデータをダウンロードしています</>
clear_game_data_q=ダウンロードしたゲームデータを全て削除しますか？ ({{y/n}}):
cleared_game_data=<@su>ゲームデータを正常に削除しました</>

validating_game_repo=ゲームデータリポジトリを検証しています...
invalid_response=<@e>無効なレスポンスコード: <@s>{response_code}</>。期待値: <@s>200</></>
no_internet_or_connection_error=<@e>ゲームデータリポジトリへの接続に失敗しました</>
invalid_url=<@e>無効な URL です</>

use_alternative_repo=<@e>ゲームデータリポジトリの取得に失敗しました。ネットワークの問題、またはリポジトリがブロックされている可能性があります。</> 代替のリポジトリ <@t>{repo}</t> に切り替えますか？ ({{y/n}}):
